### ISSUE TITLE
只支持MySql吗？

### ISSUE THREAD

**Issue by zyhhb** [dblabai/dblab#1]
目前在官网下载的版本只有MySql可选，什么时候可连接文档示例中的其他数据库呢？
![image](https://github.com/dblabai/dblab/assets/3205293/54f15f28-2419-4bef-acee-56d5e997e6b1)

**Comment by dblabai** [comment]
目前**2024.1版本**只开放**MySQL数据库**的支持，我们将在后续版本中陆续对更多的数据库进行开放与支持！
您可以在[征求数据库支持反馈](https://github.com/dblabai/dblab/discussions/2#discussion-6237365)页面进行投票讨论。
感谢您的支持！

**Comment by dblabai** [comment]
**2024.1.3-beta**版本 已开放**Redis**数据库支持！

**Comment by dblabai** [comment]
2024.2.0-beta版本已开放PostgreSQL数据库支持！
