### ISSUE TITLE
[Feature]: 希望在右键表时增加复制选项用来复制表名

### ISSUE THREAD

**Issue by csch961207** [dblabai/dblab#4]
ai功能省去了我编写sql但我在使用ai时总会需要输入表名或字段名，复制是最快速而不易出错的，通过其他方式也能得到但我希望有一个更快捷的方式
希望在这里添加功能
![image](https://github.com/dblabai/dblab/assets/48863231/33ce5b42-ec21-402c-9f1b-cbc387c7bfb8)
![image](https://github.com/dblabai/dblab/assets/48863231/4df6362f-6256-4827-824e-8516406030eb)
同时希望字段也是如此

**Comment by dblabai** [comment]
在**数据库管理区域**可以通过`Ctrl+C`的方式复制表名/字段名等；也可以通过拖动的方式将表名/字段名等拖动到AI助手输入框或者SQL编辑器中。

**Comment by dblabai** [comment]
该功能已在2024.1.6-beta版本中添加，请更新至2024.1.6-beta以上版本。
