### ISSUE TITLE
[Bug]: 复制一行数据在粘贴的时候null会被转换为空字符串

### ISSUE THREAD

**Issue by csch961207** [dblabai/dblab#6]
如下图，我不想要这种替换
![image](https://github.com/dblabai/dblab/assets/48863231/b3625a27-12c5-499a-8ddb-c4c94cc89e26)

**Comment by dblabai** [comment]
感谢您的反馈，该问题已在2024.1.6-beta版本中修复，请更新至2024.1.6-beta以上版本。
