### ISSUE TITLE
[Feature]: 希望可以增加自定义AI模型的配置

### ISSUE THREAD

**Issue by xyx007** [dblabai/dblab#7]
使用过程中发现AI助手不够聪明, 就算选中表还是会生成非表中字段的sql, 希望能增加自定义AI模型的配置, 可以使用其他的AI模型chat

**Comment by dblabai** [comment]
感谢您的反馈，我们已在2024.2.4-beta版本中新增了多AI模型支持，请更新至2024.2.4-beta以上版本。
